services:

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
        PORT: 3000
        NODE_ENV: development
        MONGO_URI: mongodb://mongo:27017/taskforge
        JWT_SECRET: ${JWT_SECRET}
        JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: