services:

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      mongoURI: mongodb://mongo:27017/taskforge
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: